version: "3"

services:
  namenode:
    image: local/hadoop-2
    build: .
    command: start-hadoop-namenode

  secondarynamenode:
    image: local/hadoop-2
    build: .
    links:
      - namenode
    command: start-hadoop-secondarynamenode

  datanode:
    deploy:
      replicas: 2
    build: .
    image: local/hadoop-2
    links:
      - namenode
      - secondarynamenode
    command: start-hadoop-datanode
