#!/usr/bin/env bash
set -x
# Starts the Hadoop data node. Expects the name node host and the daemon flag
# as parameters

# source /etc/bash.bashrc

# Wait for the name node to be online
while ! nc -z namenode 50070; do
  sleep 2;
done;

# Start HDFS data node
# sed -i.bak "s|\[NAMENODE_HOST\]|${1}|g" $HADOOP_CONF_DIR/core-site.xml
# rm -f $HADOOP_CONF_DIR/core-site.xml.bak

hdfs datanode

#hadoop-daemon.sh start datanode
# # Start daemon if specified
# if [[ "${2}" != 'daemon' ]]; then
#    tail -f /dev/null
# fi
